name: sport_exchange
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  auto_route: ^7.8.4
  build_runner: ^2.4.7

  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.1
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 200

        - asset: fonts/Montserrat-Light.ttf
          weight: 300

        - asset: fonts/Montserrat-Regular.ttf
          weight: 400

        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500

        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
          
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-ExtraLight.ttf
          weight: 200

        - asset: fonts/Oswald-Light.ttf
          weight: 300

        - asset: fonts/Oswald-Regular.ttf
          weight: 400

        - asset: fonts/Oswald-Medium.ttf
          weight: 500

        - asset: fonts/Oswald-SemiBold.ttf
          weight: 600

        - asset: fonts/Oswald-Bold.ttf
          weight: 700